// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: api/nafmock/v1/nafmock.proto

package nafmockv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NAFMock_ApplyOperation_FullMethodName = "/nafmock.v1.NAFMock/ApplyOperation"
)

// NAFMockClient is the client API for NAFMock service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NAFMockClient interface {
	ApplyOperation(ctx context.Context, in *ApplyOperationRequest, opts ...grpc.CallOption) (*ApplyOperationResponse, error)
}

type nAFMockClient struct {
	cc grpc.ClientConnInterface
}

func NewNAFMockClient(cc grpc.ClientConnInterface) NAFMockClient {
	return &nAFMockClient{cc}
}

func (c *nAFMockClient) ApplyOperation(ctx context.Context, in *ApplyOperationRequest, opts ...grpc.CallOption) (*ApplyOperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyOperationResponse)
	err := c.cc.Invoke(ctx, NAFMock_ApplyOperation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NAFMockServer is the server API for NAFMock service.
// All implementations must embed UnimplementedNAFMockServer
// for forward compatibility.
type NAFMockServer interface {
	ApplyOperation(context.Context, *ApplyOperationRequest) (*ApplyOperationResponse, error)
	mustEmbedUnimplementedNAFMockServer()
}

// UnimplementedNAFMockServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNAFMockServer struct{}

func (UnimplementedNAFMockServer) ApplyOperation(context.Context, *ApplyOperationRequest) (*ApplyOperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyOperation not implemented")
}
func (UnimplementedNAFMockServer) mustEmbedUnimplementedNAFMockServer() {}
func (UnimplementedNAFMockServer) testEmbeddedByValue()                 {}

// UnsafeNAFMockServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NAFMockServer will
// result in compilation errors.
type UnsafeNAFMockServer interface {
	mustEmbedUnimplementedNAFMockServer()
}

func RegisterNAFMockServer(s grpc.ServiceRegistrar, srv NAFMockServer) {
	// If the following call panics, it indicates UnimplementedNAFMockServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NAFMock_ServiceDesc, srv)
}

func _NAFMock_ApplyOperation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyOperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NAFMockServer).ApplyOperation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NAFMock_ApplyOperation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NAFMockServer).ApplyOperation(ctx, req.(*ApplyOperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NAFMock_ServiceDesc is the grpc.ServiceDesc for NAFMock service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NAFMock_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nafmock.v1.NAFMock",
	HandlerType: (*NAFMockServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ApplyOperation",
			Handler:    _NAFMock_ApplyOperation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/nafmock/v1/nafmock.proto",
}
