// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.3
// source: api/nafmock/v1/nafmock.proto

package nafmockv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApplyOperationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operation     string                 `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyOperationRequest) Reset() {
	*x = ApplyOperationRequest{}
	mi := &file_api_nafmock_v1_nafmock_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyOperationRequest) ProtoMessage() {}

func (x *ApplyOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_nafmock_v1_nafmock_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyOperationRequest.ProtoReflect.Descriptor instead.
func (*ApplyOperationRequest) Descriptor() ([]byte, []int) {
	return file_api_nafmock_v1_nafmock_proto_rawDescGZIP(), []int{0}
}

func (x *ApplyOperationRequest) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *ApplyOperationRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ApplyOperationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handle        string                 `protobuf:"bytes,1,opt,name=handle,proto3" json:"handle,omitempty"`
	AppliedAt     string                 `protobuf:"bytes,2,opt,name=applied_at,json=appliedAt,proto3" json:"applied_at,omitempty"`
	Echo          []byte                 `protobuf:"bytes,3,opt,name=echo,proto3" json:"echo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyOperationResponse) Reset() {
	*x = ApplyOperationResponse{}
	mi := &file_api_nafmock_v1_nafmock_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyOperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyOperationResponse) ProtoMessage() {}

func (x *ApplyOperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_nafmock_v1_nafmock_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyOperationResponse.ProtoReflect.Descriptor instead.
func (*ApplyOperationResponse) Descriptor() ([]byte, []int) {
	return file_api_nafmock_v1_nafmock_proto_rawDescGZIP(), []int{1}
}

func (x *ApplyOperationResponse) GetHandle() string {
	if x != nil {
		return x.Handle
	}
	return ""
}

func (x *ApplyOperationResponse) GetAppliedAt() string {
	if x != nil {
		return x.AppliedAt
	}
	return ""
}

func (x *ApplyOperationResponse) GetEcho() []byte {
	if x != nil {
		return x.Echo
	}
	return nil
}

var File_api_nafmock_v1_nafmock_proto protoreflect.FileDescriptor

const file_api_nafmock_v1_nafmock_proto_rawDesc = "" +
	"\n" +
	"\x1capi/nafmock/v1/nafmock.proto\x12\n" +
	"nafmock.v1\"O\n" +
	"\x15ApplyOperationRequest\x12\x1c\n" +
	"\toperation\x18\x01 \x01(\tR\toperation\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"c\n" +
	"\x16ApplyOperationResponse\x12\x16\n" +
	"\x06handle\x18\x01 \x01(\tR\x06handle\x12\x1d\n" +
	"\n" +
	"applied_at\x18\x02 \x01(\tR\tappliedAt\x12\x12\n" +
	"\x04echo\x18\x03 \x01(\fR\x04echo2b\n" +
	"\aNAFMock\x12W\n" +
	"\x0eApplyOperation\x12!.nafmock.v1.ApplyOperationRequest\x1a\".nafmock.v1.ApplyOperationResponseBqZogithub.com/allenabishekGithub/platform_engineering_skills/gateway-week/mock-grpcServer/api/nafmock/v1;nafmockv1b\x06proto3"

var (
	file_api_nafmock_v1_nafmock_proto_rawDescOnce sync.Once
	file_api_nafmock_v1_nafmock_proto_rawDescData []byte
)

func file_api_nafmock_v1_nafmock_proto_rawDescGZIP() []byte {
	file_api_nafmock_v1_nafmock_proto_rawDescOnce.Do(func() {
		file_api_nafmock_v1_nafmock_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_nafmock_v1_nafmock_proto_rawDesc), len(file_api_nafmock_v1_nafmock_proto_rawDesc)))
	})
	return file_api_nafmock_v1_nafmock_proto_rawDescData
}

var file_api_nafmock_v1_nafmock_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_nafmock_v1_nafmock_proto_goTypes = []any{
	(*ApplyOperationRequest)(nil),  // 0: nafmock.v1.ApplyOperationRequest
	(*ApplyOperationResponse)(nil), // 1: nafmock.v1.ApplyOperationResponse
}
var file_api_nafmock_v1_nafmock_proto_depIdxs = []int32{
	0, // 0: nafmock.v1.NAFMock.ApplyOperation:input_type -> nafmock.v1.ApplyOperationRequest
	1, // 1: nafmock.v1.NAFMock.ApplyOperation:output_type -> nafmock.v1.ApplyOperationResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_nafmock_v1_nafmock_proto_init() }
func file_api_nafmock_v1_nafmock_proto_init() {
	if File_api_nafmock_v1_nafmock_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_nafmock_v1_nafmock_proto_rawDesc), len(file_api_nafmock_v1_nafmock_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_nafmock_v1_nafmock_proto_goTypes,
		DependencyIndexes: file_api_nafmock_v1_nafmock_proto_depIdxs,
		MessageInfos:      file_api_nafmock_v1_nafmock_proto_msgTypes,
	}.Build()
	File_api_nafmock_v1_nafmock_proto = out.File
	file_api_nafmock_v1_nafmock_proto_goTypes = nil
	file_api_nafmock_v1_nafmock_proto_depIdxs = nil
}
