# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from api.nafmock.v1 import nafmock_pb2 as api_dot_nafmock_dot_v1_dot_nafmock__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in api/nafmock/v1/nafmock_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NAFMockStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ApplyOperation = channel.unary_unary(
                '/nafmock.v1.NAFMock/ApplyOperation',
                request_serializer=api_dot_nafmock_dot_v1_dot_nafmock__pb2.ApplyOperationRequest.SerializeToString,
                response_deserializer=api_dot_nafmock_dot_v1_dot_nafmock__pb2.ApplyOperationResponse.FromString,
                _registered_method=True)


class NAFMockServicer:
    """Missing associated documentation comment in .proto file."""

    def ApplyOperation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NAFMockServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ApplyOperation': grpc.unary_unary_rpc_method_handler(
                    servicer.ApplyOperation,
                    request_deserializer=api_dot_nafmock_dot_v1_dot_nafmock__pb2.ApplyOperationRequest.FromString,
                    response_serializer=api_dot_nafmock_dot_v1_dot_nafmock__pb2.ApplyOperationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nafmock.v1.NAFMock', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('nafmock.v1.NAFMock', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NAFMock:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ApplyOperation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nafmock.v1.NAFMock/ApplyOperation',
            api_dot_nafmock_dot_v1_dot_nafmock__pb2.ApplyOperationRequest.SerializeToString,
            api_dot_nafmock_dot_v1_dot_nafmock__pb2.ApplyOperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
