# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/nafmock/v1/nafmock.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'api/nafmock/v1/nafmock.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x61pi/nafmock/v1/nafmock.proto\x12\nnafmock.v1\";\n\x15\x41pplyOperationRequest\x12\x11\n\toperation\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\"J\n\x16\x41pplyOperationResponse\x12\x0e\n\x06handle\x18\x01 \x01(\t\x12\x12\n\napplied_at\x18\x02 \x01(\t\x12\x0c\n\x04\x65\x63ho\x18\x03 \x01(\x0c\x32\x62\n\x07NAFMock\x12W\n\x0e\x41pplyOperation\x12!.nafmock.v1.ApplyOperationRequest\x1a\".nafmock.v1.ApplyOperationResponseBqZogithub.com/allenabishekGithub/platform_engineering_skills/gateway-week/mock-grpcServer/api/nafmock/v1;nafmockv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.nafmock.v1.nafmock_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Zogithub.com/allenabishekGithub/platform_engineering_skills/gateway-week/mock-grpcServer/api/nafmock/v1;nafmockv1'
  _globals['_APPLYOPERATIONREQUEST']._serialized_start=44
  _globals['_APPLYOPERATIONREQUEST']._serialized_end=103
  _globals['_APPLYOPERATIONRESPONSE']._serialized_start=105
  _globals['_APPLYOPERATIONRESPONSE']._serialized_end=179
  _globals['_NAFMOCK']._serialized_start=181
  _globals['_NAFMOCK']._serialized_end=279
# @@protoc_insertion_point(module_scope)
